### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method (cumi.py)

### ISSUE THREAD

**Issue by hxj5** [hxj5/scCNASim#2]
With Python 3.7:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/rthuang/anaconda3/envs/XCL-PRE/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/rthuang/anaconda3/envs/XCL-PRE/lib/python3.7/site-packages/sccnvsim/rs/cumi.py", line 164, in gen_umis_thread
    dat[c][k][i].append(x[r:(r+X[i, j])])
TypeError: slice indices must be integers or None or have an __index__ method
"""
```

**Comment by hxj5** [comment]
Everything works well with Python `3.11` (3.11.9). 
We have listed the requirement/dependency of Python version (i.e., Python>=3.11) in the `setup.py` and relevant docs.

**Comment by hxj5** [comment]
The same issue when using Python `3.9` (3.9.19). Not sure which dependency (e.g., numpy, pandas, anndata) is not compatible with the codes.
